language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/travis:${PATH}
  - travis_install_nightly ${VERSION}
  - travis_install_mx_nightly ${VERSION}

script:
  - git clone https://github.com/vauxoo/addons-vauxoo ${HOME}/addons-vauxoo -b ${VERSION}
  #- travis_run_flake8 #first time many errors
  #- travis_run_pylint #first time many errors
  - travis_run_tests ${VERSION}

after_success:
  coveralls
  
